### ISSUE TITLE
License

### ISSUE THREAD

**Issue by DemiMarie** [InnocentusLime/TRust#15]
What license is this project under?

**Comment by InnocentusLime** [comment]
Hello!

This project hasn't been licensed yet due to the project experiencing several rewrites. I might get it some open-source license in the future, but for now this repository is just a blob of code.

Apologies for taking several months to reply.

**Comment by InnocentusLime** [comment]
Closing this issue. The code in the repository is now available under the MIT license as of 718e5f271e383c32a6df4ead302773bac892b259
